import type { Metadata } from "next";
import { Poppins  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const poppins = Poppins({ subsets: ["latin"], weight: ['300', '400', '500'] });

export const metadata: Metadata = {
  title: "Nuartha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="w-full">
          <Navbar />
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
